# create table issue

CREATE TABLE ISSUE(
ISSUE_ID VARCHAR(20) NOT NULL,
ISSUE_NAME VARCHAR(500) NOT NULL,
ISSUE_CREATION_TIME VARCHAR(100),
ISSUE_ACTION_PERFORMED VARCHAR(100),
ISSUE_USER_NAME VARCHAR(100),
PRIMARY KEY ( ISSUE_ID )
);

# create table milestone
CREATE TABLE MILESTONE(
MILESTONE_ID VARCHAR(20) NOT NULL,
MILESTONE_DESC VARCHAR(1000),
MILESTONE_CREATION_TIME VARCHAR(100),
MILESTONE_DUE_TIME VARCHAR(100),
MILESTONE_CLOSED_TIME VARCHAR(100),
MILESTONE_USER_NAME VARCHAR(100),
PRIMARY KEY ( MILESTONE_ID )
);

# create table comment
CREATE TABLE COMMENT(
COMMENT_ID VARCHAR(20) NOT NULL,
COMMENT_USER_ID VARCHAR(20),
COMMENT_ISSUE_ID VARCHAR(20),
COMMENT_TIMESTAMP VARCHAR(100),
COMMENT_DESC VARCHAR(1000),
PRIMARY KEY ( COMMENT_ID )
);

# create table commit
CREATE TABLE COMMIT(
COMMIT_ID VARCHAR(20) NOT NULL,
COMMIT_USER_ID VARCHAR(20),
COMMIT_TIMESTAMP VARCHAR(100),
COMMIT_DESC VARCHAR(1000),
PRIMARY KEY ( COMMIT_ID )
);